baseurl         = "https://scholz.github.io"
theme           = "casper-two"
languageCode    = "en-US"
#disqusShortname = "scholz dev postings"
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Markus Scholz"
  subtitle    = "Developer Musings"

  cover       = "cover.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  #twitterName = "faketryghost"
  #fbName = "fakeghost"
  githubName = "scholz"

  author = "Markus Scholz"
  authorAvatar = "avatar.png"
  #authorAvatar = "img/ghost-icon.png"
  authorLocation = "Karlsruhe, Germany"
  authorWebsite = "https://scholz.github.io"
  authorDescription = "Developer"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "caspertwo"

[permalinks]
 #  post = "/:year/:month/:slug/"
   post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Blog"
  url = "/tags/blog/"
  weight = 100

[[menu.main]]
  name = "Projects"
  url = "/tags/projects/"
  weight = 99

[[menu.main]]
  name = "About"
  #url = "/category/about/"
  url = "/tags/about/"
  weight = 98
